FROM ubuntu:16.04

ENV LANG en_US.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    clang-format \
    wget \
    cmake \
    make \
    valgrind \
    wget \
    && apt-get -yqq clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH /opt/miniconda3/bin:$PATH
ENV LD_LIBRARY_PATH /opt/miniconda3/lib:$LD_LIBRARY_PATH

ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ENV PYVERNAME=${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}

RUN umask 0 \
    && mkdir -p /tmp/deps \
    && cd /tmp/deps \
    && wget --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 \
    && rm -rf Miniconda3-latest-Linux-x86_64.sh \
    && conda install -y python=${PYVERNAME} \
    && pip install Cython autopep8 boto3 \
       configparser contextlib2 futures h5py mako \
       numpy protobuf pyyaml requests scikit-image scipy tqdm pytest \
    && cd / \
    && rm -rf /tmp/*

