FROM ubuntu:18.04

ENV LANG en_US.UTF-8

ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ENV PYVERNAME=${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    clang-format \
    wget \
    cmake \
    make \
    valgrind \
    wget \
    python${PYVERNAME} \
    python3-pip \
    && apt-get -yqq clean \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYVERNAME} 0
RUN update-alternatives --install /usr/bin/python python /usr/bin/python${PYVERNAME} 0

RUN pip3 install --upgrade pip
RUN pip install wheel setuptools
RUN pip install Cython autopep8 boto3 configparser \
    contextlib2 futures h5py mako numpy protobuf pyyaml requests scikit-image scipy tqdm pytest

ENV LD_LIBRARY_PATH /usr/local/lib64:$LD_LIBRARY_PATH
